name: Send OIDC Token to Python App

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  send_token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
        
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)

      - name: Send OIDC Token to Python App
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"oidc_token": "${{ steps.idtoken.outputs.id_token }}"}' \
          https://dygixku4ksw7onudfudngsiode0jfano.lambda-url.eu-west-1.on.aws/

